# Generated by Django 3.1.7 on 2021-08-23 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='老师姓名')),
                ('telephone', models.CharField(max_length=100, unique=True, verbose_name='老师电话')),
                ('gender', models.CharField(choices=[('F', '女'), ('M', '男')], default='M', max_length=3, verbose_name='性别')),
                ('status', models.CharField(choices=[('Y', '在职'), ('N', '离职')], default='Y', max_length=2, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '老师管理',
                'verbose_name_plural': '老师管理',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='学员姓名')),
                ('telephone', models.CharField(max_length=100, unique=True, verbose_name='学员电话')),
                ('gender', models.CharField(choices=[('F', '女'), ('M', '男')], default='M', max_length=3, verbose_name='性别')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '学员管理',
                'verbose_name_plural': '学员管理',
            },
        ),
        migrations.CreateModel(
            name='VipProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='会员卡名称')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('count', models.IntegerField(verbose_name='次数')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '会员卡课程管理',
                'verbose_name_plural': '会员卡课程管理',
            },
        ),
        migrations.CreateModel(
            name='VipProductOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='购买消费金额')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单次课程金额')),
                ('count', models.IntegerField(verbose_name='购买课程次数')),
                ('remain_count', models.IntegerField(default=0, verbose_name='剩余次数')),
                ('start_date', models.DateField(blank=True, default=None, null=True, verbose_name='有效期开始日期')),
                ('deadline_date', models.DateField(blank=True, default=None, null=True, verbose_name='有效期截止日期')),
                ('state', models.IntegerField(choices=[(1, '已创建'), (2, '已付款'), (3, '已取消')], default=1, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.vipproduct', verbose_name='课程名称')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.user', verbose_name='学员')),
            ],
            options={
                'verbose_name': '购买课程记录',
                'verbose_name_plural': '购买课程记录',
            },
        ),
        migrations.CreateModel(
            name='CourseRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reservation_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='预约时间')),
                ('start_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='课程开始时间')),
                ('end_date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='课程结束时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('state', models.IntegerField(choices=[(1, '已预约'), (2, '已签到'), (3, '已取消')], default=1, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('product_order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='app01.vipproductorder', verbose_name='课程名称')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.teacher', verbose_name='老师')),
            ],
            options={
                'verbose_name': '上课记录',
                'verbose_name_plural': '上课记录',
            },
        ),
    ]
