# Generated by Django 3.1.7 on 2021-08-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_card',
            field=models.CharField(default=1, max_length=30, verbose_name='学员身份证'),
            preserve_default=False,
        ),
    ]
